import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bibleBridgeSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🏠 Welcome',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 1: In the Beginning',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'part-01',
        },
      ],
    },
  ],
};

export default sidebars;
